US_STOCKS = [
    ("AAPL",  "Apple Inc.",               "Technology"),
    ("MSFT",  "Microsoft Corp.",          "Technology"),
    ("GOOGL", "Alphabet Inc.",            "Technology"),
    ("META",  "Meta Platforms",           "Technology"),
    ("AMZN",  "Amazon.com Inc.",          "Technology"),
    ("NVDA",  "NVIDIA Corp.",             "Semiconductors"),
    ("TSLA",  "Tesla Inc.",               "EV/Tech"),
    ("AVGO",  "Broadcom Inc.",            "Semiconductors"),
    ("AMD",   "Advanced Micro Devices",   "Semiconductors"),
    ("NFLX",  "Netflix Inc.",             "Streaming"),
    ("CRM",   "Salesforce Inc.",          "SaaS"),
    ("NOW",   "ServiceNow Inc.",          "SaaS"),
    ("PLTR",  "Palantir Technologies",    "AI/Data"),
    ("CRWD",  "CrowdStrike Holdings",     "Security"),
    ("DDOG",  "Datadog Inc.",             "SaaS"),
    ("SHOP",  "Shopify Inc.",             "E-Commerce"),
    ("SNOW",  "Snowflake Inc.",           "Data Cloud"),
    ("SQ",    "Block Inc.",               "Fintech"),
    ("UBER",  "Uber Technologies",        "Platform"),
    ("ABNB",  "Airbnb Inc.",              "Platform"),
]

JP_STOCKS = [
    ("9984.T", "ソフトバンクグループ",  "IT投資"),
    ("6758.T", "ソニーグループ",        "総合テック"),
    ("6861.T", "キーエンス",            "FA/センサー"),
    ("8035.T", "東京エレクトロン",      "半導体製造装置"),
    ("6920.T", "レーザーテック",        "半導体検査"),
    ("6857.T", "アドバンテスト",        "半導体テスト"),
    ("6146.T", "ディスコ",              "半導体加工"),
    ("4063.T", "信越化学工業",          "半導体材料"),
    ("6702.T", "富士通",                "ITサービス"),
    ("9432.T", "NTT",                   "通信"),
    ("9433.T", "KDDI",                  "通信"),
    ("4755.T", "楽天グループ",          "EC/Fintech"),
    ("4751.T", "サイバーエージェント",  "デジタル広告"),
    ("9449.T", "GMOインターネット",     "ネット"),
    ("3994.T", "マネーフォワード",      "Fintech SaaS"),
    ("4478.T", "freee",                 "会計SaaS"),
    ("4443.T", "Sansan",                "BizSaaS"),
    ("4180.T", "Appier",                "AI広告"),
    ("6501.T", "日立製作所",            "ITサービス"),
    ("3697.T", "SHIFT",                 "ITコンサル"),
]
